### ISSUE TITLE
搞个action版本的？

### ISSUE THREAD

**Issue by pino889** [WuliAPO/Fuck_QCZJ#5]

**Comment by WuliAPO** [comment]
暂时没有这个打算。我已经把脚本放在自己的服务器了，你可以直接部署在服务器上，或者自己写一下action

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by moye12325** [comment]
之前我根据别人的改的
```
name: 'GitHub Actions'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 14 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Action
      run: |
        cd Action
        sh start.sh
    - name: Commit
      run: |
          git config --global user.email 邮箱
          git config --global user.name GitHub用户名
          git add *
          #git commit -m"action:`date +'%Y-%m-%d'`"
          git commit -m "action:`date`"
          git push origin master
```
